[package]
name = "purs"
version = "0.3.0"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
ansi_term = "0.12.1"
clap = "4.0.32"
git2 = "0.15.0"
nix = "0.26.1"
tico = "2.0.0"
