[package]
name = "purs"
version = "0.3.1"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[dependencies]
clap = { version = "4.2.1", default-features = false, features = [ "std", "help", "usage" ] }
git2 = "0.17.0"
nix = { version = "0.26.2", default-features = false, features = [ "hostname" ] }
colored = "2"
