[package]
name = "purs"
version = "0.1.2"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
ansi_term = "0.12.1"
clap = "2.33.3"
dirs = "3.0.2"
failure = "0.1.8"
git2 = "0.14.1"
nix = "0.22.0"
regex = "1.5.4"
tico = "2.0.0"
