[package]
name = "purs"
version = "0.1.2"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
ansi_term = "0.12.1"
clap = "2.34.0"
dirs = "4.0.0"
failure = "0.1.8"
git2 = "0.15.0"
nix = "0.24.2"
regex = "1.7.0"
tico = "2.0.0"
