[package]
name = "purs"
version = "0.3.0"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
clap = "4.1.1"
git2 = "0.16.0"
nix = "0.26.2"
colored = "2"
