[package]
name = "purs"
version = "0.3.2"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[dependencies]
clap = { version = "4.2.2", default-features = false, features = ["std", "help"] }
git2 = { default-features = false, version = "0.17.1" }
nix = { version = "0.26.2", default-features = false, features = [ "hostname" ] }
colored = "2"
